import { createFeatureSelector, createSelector } from '@ngrx/store';
import { MediaState, adapter } from '../reducers/media.reducer';

// Feature selector for the media state
export const selectMediaState = createFeatureSelector<MediaState>('media');

// Entity selectors generated by the entity adapter
export const { selectAll: selectAllMediaItems } = adapter.getSelectors(
  selectMediaState
);

// Selector for loaded state
export const selectMediaLoaded = createSelector(
  selectMediaState,
  (state: MediaState) => state.loaded
);
